version: '3'
services:
  api:
    build: ./api
    ports:
      - "5000:5000"
    environment:
      - API_DB=${API_DB}

  web:
    build: ./web
    ports:
      - "3000:3000"
    environment:
      - API_HOST=api
