version: '3'
services:
  api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./:/app/
    working_dir: /app
    command: npm start
    environment:
      - PORT=5000
      - DB=${API_DB}
