version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app/
    working_dir: /app
    command: npm start
    environment:
      - PORT=3000
      - API_HOST=${API_HOST}

